#!/bin/bash
# generate_api_data.sh — Generate api_data.js from GXLib headers
# Usage: bash docs/generate_api_data.sh
# Output: docs/api_data.js

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GXLIB_DIR="$PROJECT_ROOT/GXLib"
OUTPUT="$SCRIPT_DIR/api_data.js"
AWK_SCRIPT="$SCRIPT_DIR/parse_headers.awk"

# Module metadata: directory_suffix|id|name|icon|description
declare -a MODULE_META=(
    "AI|ai|AI|🧠|AI・ナビゲーション — NavMesh, BehaviorTree, GOAP"
    "Audio|audio|Audio|🔊|オーディオ — デバイス, ミキサー, エフェクト, 3Dサウンド"
    "Compat|compat|Compat|🔄|DxLib互換レイヤー"
    "Core/Reflect|reflect|Reflect|🪞|リフレクション・型情報"
    "Core/Scene|scene|Scene|🎬|シーン・エンティティ・コンポーネント"
    "Core|core|Core|⚙️|コアシステム — アプリ, ウィンドウ, タイマー, ログ"
    "ECS|ecs|ECS|🧩|データ指向ECS — World, Archetype, Query"
    "Editor|editor|Editor|🛠️|エディタ — ギズモ, エンティティピッカー"
    "GUI/Widgets|gui_widgets|GUI Widgets|🧱|GUIウィジェット — Button, Slider, ListView等"
    "GUI|gui|GUI|🖼️|GUIシステム — UIContext, スタイルシート, レンダラー"
    "GX|gx|GX Easy|🎮|簡易API — App, Draw2D, Input, Math, Text"
    "Graphics/3D|gfx3d|Graphics 3D|🎲|3Dグラフィックス — メッシュ, マテリアル, ライト, アニメーション"
    "Graphics/Device|gfx_device|Device|🖥️|DirectX 12デバイス — コマンドリスト, スワップチェーン"
    "Graphics/FrameGraph|gfx_framegraph|FrameGraph|📊|フレームグラフ — レンダーパス自動管理"
    "Graphics/Layer|gfx_layer|Layer|📑|レイヤー合成・マスク"
    "Graphics/Pipeline|gfx_pipeline|Pipeline|🔧|パイプライン — シェーダー, PSO, ルートシグネチャ"
    "Graphics/PostEffect|gfx_postfx|PostEffect|✨|ポストエフェクト — Bloom, SSAO, SSR, TAA, DOF"
    "Graphics/RayTracing|gfx_rt|RayTracing|💫|レイトレーシング — RTGI, RTReflections"
    "Graphics/Rendering|gfx_render|Rendering 2D|🎨|2D描画 — スプライト, テキスト, パーティクル"
    "Graphics/Resource|gfx_resource|Resource|📦|GPUリソース — テクスチャ, バッファ, レンダーターゲット"
    "Graphics/Text|gfx_text|Text|🔤|テキスト描画(DirectWrite)"
    "IO/Network|io_net|Network|🌐|ネットワーク — TCP, UDP, WebSocket, HTTP"
    "IO|io|IO|💾|ファイルI/O — アーカイブ, 暗号化, 非同期ロード"
    "Input|input|Input|🎹|入力 — キーボード, マウス, ゲームパッド, アクションマッピング"
    "Math/Collision|math_collision|Collision|💥|衝突判定 — BVH, Octree, Quadtree, GJK"
    "Math|math|Math|∑|数学 — ベクトル, 行列, クォータニオン, 乱数, スプライン"
    "Movie|movie|Movie|🎞️|動画再生"
    "Physics|physics|Physics|🏗️|物理演算 — RigidBody, PhysicsWorld, コライダー"
    "Script|script|Script|📜|Luaスクリプト — ScriptEngine, バインディング"
)

# Collect all header files, excluding ThirdParty and pch
mapfile -t HEADERS < <(find "$GXLIB_DIR" -name "*.h" \
    ! -path "*/ThirdParty/*" \
    ! -name "pch*.h" \
    | sort)

echo "// Scanning ${#HEADERS[@]} header files..." >&2

# Run the AWK parser on all headers
RAW_DATA=$(awk -f "$AWK_SCRIPT" "${HEADERS[@]}" 2>/dev/null || true)

# Now build the JS data file
cat > "$OUTPUT" << 'HEADER'
// api_data.js — Auto-generated GXLib API reference data
// Generated by generate_api_data.sh
/* eslint-disable */
var GX_API_DATA = (function() {
"use strict";
HEADER

# Emit module metadata
echo "var modules = {" >> "$OUTPUT"
first_mod=1
for meta in "${MODULE_META[@]}"; do
    IFS='|' read -r dir_suffix mod_id mod_name mod_icon mod_desc <<< "$meta"
    if [ $first_mod -eq 0 ]; then echo "," >> "$OUTPUT"; fi
    first_mod=0
    printf '  "%s": {"name":"%s","icon":"%s","desc":"%s","dir":"%s","files":{}}' \
        "$mod_id" "$mod_name" "$mod_icon" "$(echo "$mod_desc" | sed 's/"/\\"/g')" "$dir_suffix" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"
echo "};" >> "$OUTPUT"

# Process raw data and organize by file, then by class/enum
echo "" >> "$OUTPUT"
echo "// --- File and type data ---" >> "$OUTPUT"
echo "var files = {};" >> "$OUTPUT"
echo "var types = [];" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Parse the ITEM lines and generate JS
echo "$RAW_DATA" | awk -v gxlib_dir="$GXLIB_DIR" '
BEGIN {
    FS="|"
    file_count = 0
    type_count = 0
    current_file = ""
    # Track which files we have seen
}

function js_str(s) {
    gsub(/\\/, "\\\\", s)
    gsub(/"/, "\\\"", s)
    return "\"" s "\""
}

$1 == "ITEM" {
    file = $2
    ns = $3
    kind = $4
    name = $5
    detail = $6
    for (i = 7; i <= NF; i++) detail = detail "|" $i

    # Make file path relative to GXLib/
    rel = file
    sub(gxlib_dir "/", "", rel)

    # Determine module from path
    module_id = ""
    # Try most specific first
    if (rel ~ /^GUI\/Widgets\//)       module_id = "gui_widgets"
    else if (rel ~ /^Graphics\/3D\//)  module_id = "gfx3d"
    else if (rel ~ /^Graphics\/Device\//) module_id = "gfx_device"
    else if (rel ~ /^Graphics\/FrameGraph\//) module_id = "gfx_framegraph"
    else if (rel ~ /^Graphics\/Layer\//) module_id = "gfx_layer"
    else if (rel ~ /^Graphics\/Pipeline\//) module_id = "gfx_pipeline"
    else if (rel ~ /^Graphics\/PostEffect\//) module_id = "gfx_postfx"
    else if (rel ~ /^Graphics\/RayTracing\//) module_id = "gfx_rt"
    else if (rel ~ /^Graphics\/Rendering\//) module_id = "gfx_render"
    else if (rel ~ /^Graphics\/Resource\//) module_id = "gfx_resource"
    else if (rel ~ /^Graphics\/Text\//) module_id = "gfx_text"
    else if (rel ~ /^IO\/Network\//)   module_id = "io_net"
    else if (rel ~ /^Core\/Reflect\//) module_id = "reflect"
    else if (rel ~ /^Core\/Scene\//)   module_id = "scene"
    else if (rel ~ /^Math\/Collision\//) module_id = "math_collision"
    else if (rel ~ /^AI\//)            module_id = "ai"
    else if (rel ~ /^Audio\//)         module_id = "audio"
    else if (rel ~ /^Compat\//)        module_id = "compat"
    else if (rel ~ /^Core\//)          module_id = "core"
    else if (rel ~ /^ECS\//)           module_id = "ecs"
    else if (rel ~ /^Editor\//)        module_id = "editor"
    else if (rel ~ /^GUI\//)           module_id = "gui"
    else if (rel ~ /^GX\//)            module_id = "gx"
    else if (rel ~ /^Graphics\//)      module_id = "gfx3d"
    else if (rel ~ /^IO\//)            module_id = "io"
    else if (rel ~ /^Input\//)         module_id = "input"
    else if (rel ~ /^Math\//)          module_id = "math"
    else if (rel ~ /^Movie\//)         module_id = "movie"
    else if (rel ~ /^Physics\//)       module_id = "physics"
    else if (rel ~ /^Script\//)        module_id = "script"
    else module_id = "core"

    # Get just the filename
    fname = rel
    gsub(/.*\//, "", fname)

    # Register file if new
    if (!(rel in seen_files)) {
        seen_files[rel] = 1
        file_count++
        printf "files[%s]={\"module\":%s,\"ns\":%s,\"items\":[]};\n", \
            js_str(rel), js_str(module_id), js_str(ns)
    }

    # Output the item
    if (kind == "class" || kind == "struct") {
        # detail = doc|bases|template
        split(detail, d, "|")
        doc = d[1]; bases = d[2]; tpl = d[3]
        type_count++
        printf "types.push({\"kind\":%s,\"name\":%s,\"file\":%s,\"module\":%s,\"ns\":%s,\"doc\":%s,\"bases\":%s,\"tpl\":%s,\"methods\":[],\"fields\":[]});\n", \
            js_str(kind), js_str(name), js_str(rel), js_str(module_id), js_str(ns), js_str(doc), js_str(bases), js_str(tpl)
        printf "files[%s].items.push({\"kind\":%s,\"name\":%s,\"idx\":%d});\n", \
            js_str(rel), js_str(kind), js_str(name), type_count - 1
    } else if (kind == "enum") {
        # detail = doc|base_type
        split(detail, d, "|")
        doc = d[1]; base_type = d[2]
        type_count++
        printf "types.push({\"kind\":\"enum\",\"name\":%s,\"file\":%s,\"module\":%s,\"ns\":%s,\"doc\":%s,\"base\":%s,\"values\":[]});\n", \
            js_str(name), js_str(rel), js_str(module_id), js_str(ns), js_str(doc), js_str(base_type)
        printf "files[%s].items.push({\"kind\":\"enum\",\"name\":%s,\"idx\":%d});\n", \
            js_str(rel), js_str(name), type_count - 1
    } else if (kind == "enumvals") {
        # Find the last enum type we pushed with this name
        # detail = val1=init1=doc1;val2=init2=doc2;...
        n = split(detail, vals, ";")
        for (v = 1; v <= n; v++) {
            split(vals[v], vp, "=")
            vname = vp[1]; vinit = vp[2]; vdoc = vp[3]
            if (vname != "") {
                printf "types[types.length-1].values.push({\"name\":%s,\"init\":%s,\"doc\":%s});\n", \
                    js_str(vname), js_str(vinit), js_str(vdoc)
            }
        }
    } else if (kind == "constns") {
        # Namespace used as constant group
        type_count++
        printf "types.push({\"kind\":\"constns\",\"name\":%s,\"file\":%s,\"module\":%s,\"ns\":%s,\"doc\":%s,\"consts\":[]});\n", \
            js_str(name), js_str(rel), js_str(module_id), js_str(ns), js_str(detail)
        printf "files[%s].items.push({\"kind\":\"constns\",\"name\":%s,\"idx\":%d});\n", \
            js_str(rel), js_str(name), type_count - 1
    } else if (kind == "const") {
        # Constant within a namespace
        printf "if(types.length>0 && types[types.length-1].kind===\"constns\"){types[types.length-1].consts.push({\"sig\":%s,\"doc\":%s});}\n", \
            js_str(name), js_str(detail)
    } else if (kind == "method") {
        # detail = sig|access|doc|qualifiers
        split(detail, d, "|")
        sig = d[1]; acc = d[2]; doc = d[3]; qual = d[4]
        # Find the last class/struct type
        printf "if(types.length>0){types[types.length-1].methods.push({\"sig\":%s,\"access\":%s,\"doc\":%s,\"qual\":%s});}\n", \
            js_str(sig), js_str(acc), js_str(doc), js_str(qual)
    } else if (kind == "field") {
        # detail = sig|access|doc|qualifiers
        split(detail, d, "|")
        sig = d[1]; acc = d[2]; doc = d[3]; qual = d[4]
        printf "if(types.length>0){types[types.length-1].fields.push({\"sig\":%s,\"access\":%s,\"doc\":%s,\"qual\":%s});}\n", \
            js_str(sig), js_str(acc), js_str(doc), js_str(qual)
    } else if (kind == "func") {
        # Free function: detail = doc|qualifiers
        split(detail, d, "|")
        doc = d[1]; qual = d[2]
        printf "files[%s].items.push({\"kind\":\"func\",\"sig\":%s,\"doc\":%s,\"qual\":%s});\n", \
            js_str(rel), js_str(name), js_str(doc), js_str(qual)
    } else if (kind == "typedef" || kind == "using") {
        printf "files[%s].items.push({\"kind\":%s,\"sig\":%s,\"doc\":%s});\n", \
            js_str(rel), js_str(kind), js_str(name), js_str(detail)
    }
}

END {
    printf "\n// Total: %d files, %d types\n", file_count, type_count
}
' >> "$OUTPUT"

# Build module -> files mapping
cat >> "$OUTPUT" << 'MAPPING'

// Build module file lists
Object.keys(files).forEach(function(path) {
    var f = files[path];
    var m = modules[f.module];
    if (m) {
        var fname = path.split("/").pop();
        m.files[path] = fname;
    }
});

MAPPING

# Close the IIFE and return the data
cat >> "$OUTPUT" << 'FOOTER'
return {
    modules: modules,
    files: files,
    types: types,
    generated: new Date().toISOString()
};
})();
FOOTER

# Report stats
file_count=$(grep -c "^files\[" "$OUTPUT" || true)
type_count=$(grep -c "^types.push" "$OUTPUT" || true)
echo "Generated $OUTPUT: $file_count files, $type_count types" >&2
